"""
Project: Reinforcement Learning Snake Agent
File: q_learning.py
Snake Eater Q learning basic algorithm

Code base originally provided by J.L.P.
(Anonymized due to lack of formal permission to publish their full name.
Credit is acknowledged for the foundational implementation developed during
Machine Learning I, Universidad Carlos III de Madrid.)

Public version prepared and maintained by:
    Felipe Grima Rodríguez
    (with collaboration of Pedro Javier López Dondarza)

License: MIT License (for educational / portfolio demonstration only)

Notes:
- This repository is a sanitized and educational adaptation of a university project.
- The original author has been anonymized; all rights and credits are preserved.
- The project demonstrates the use of tabular Q-learning in a PyGame-based environment.
"""

import numpy as np
import random
import json
import time

class QLearning:
    def __init__(self, n_states, n_actions, alpha=0.5, gamma=0.9, epsilon=0, epsilon_min=0.00, epsilon_decay=0.9999):
        self.n_states = n_states
        self.n_actions = n_actions
        self.actions = {"UP": 0, "DOWN": 1, "LEFT": 2, "RIGHT": 3}
        self.states ={
    ('UP', 'EAT', 'DOWN'): 0,
    ('UP', 'EAT', 'LEFT'): 1,
    ('UP', 'EAT', 'RIGHT'): 2,
    ('UP', 'EAT', 'UP'): 3,
    ('UP', 'EAT', 'DOWN-LEFT'): 4,
    ('UP', 'EAT', 'DOWN-RIGHT'): 5,
    ('UP', 'EAT', 'DOWN-UP'): 6,
    ('UP', 'EAT', 'LEFT-RIGHT'): 7,
    ('UP', 'EAT', 'LEFT-UP'): 8,
    ('UP', 'EAT', 'RIGHT-UP'): 9,
    ('UP', 'EAT', 'DOWN-LEFT-RIGHT'): 10,
    ('UP', 'EAT', 'DOWN-LEFT-UP'): 11,
    ('UP', 'EAT', 'DOWN-RIGHT-UP'): 12,
    ('UP', 'EAT', 'LEFT-RIGHT-UP'): 13,
    ('UP', 'EAT', 'DOWN-LEFT-RIGHT-UP'): 14,
    ('UP', 'NORTH', 'DOWN'): 15,
    ('UP', 'NORTH', 'LEFT'): 16,
    ('UP', 'NORTH', 'RIGHT'): 17,
    ('UP', 'NORTH', 'UP'): 18,
    ('UP', 'NORTH', 'DOWN-LEFT'): 19,
    ('UP', 'NORTH', 'DOWN-RIGHT'): 20,
    ('UP', 'NORTH', 'DOWN-UP'): 21,
    ('UP', 'NORTH', 'LEFT-RIGHT'): 22,
    ('UP', 'NORTH', 'LEFT-UP'): 23,
    ('UP', 'NORTH', 'RIGHT-UP'): 24,
    ('UP', 'NORTH', 'DOWN-LEFT-RIGHT'): 25,
    ('UP', 'NORTH', 'DOWN-LEFT-UP'): 26,
    ('UP', 'NORTH', 'DOWN-RIGHT-UP'): 27,
    ('UP', 'NORTH', 'LEFT-RIGHT-UP'): 28,
    ('UP', 'NORTH', 'DOWN-LEFT-RIGHT-UP'): 29,
    ('UP', 'SOUTH', 'DOWN'): 30,
    ('UP', 'SOUTH', 'LEFT'): 31,
    ('UP', 'SOUTH', 'RIGHT'): 32,
    ('UP', 'SOUTH', 'UP'): 33,
    ('UP', 'SOUTH', 'DOWN-LEFT'): 34,
    ('UP', 'SOUTH', 'DOWN-RIGHT'): 35,
    ('UP', 'SOUTH', 'DOWN-UP'): 36,
    ('UP', 'SOUTH', 'LEFT-RIGHT'): 37,
    ('UP', 'SOUTH', 'LEFT-UP'): 38,
    ('UP', 'SOUTH', 'RIGHT-UP'): 39,
    ('UP', 'SOUTH', 'DOWN-LEFT-RIGHT'): 40,
    ('UP', 'SOUTH', 'DOWN-LEFT-UP'): 41,
    ('UP', 'SOUTH', 'DOWN-RIGHT-UP'): 42,
    ('UP', 'SOUTH', 'LEFT-RIGHT-UP'): 43,
    ('UP', 'SOUTH', 'DOWN-LEFT-RIGHT-UP'): 44,
    ('UP', 'WEST', 'DOWN'): 45,
    ('UP', 'WEST', 'LEFT'): 46,
    ('UP', 'WEST', 'RIGHT'): 47,
    ('UP', 'WEST', 'UP'): 48,
    ('UP', 'WEST', 'DOWN-LEFT'): 49,
    ('UP', 'WEST', 'DOWN-RIGHT'): 50,
    ('UP', 'WEST', 'DOWN-UP'): 51,
    ('UP', 'WEST', 'LEFT-RIGHT'): 52,
    ('UP', 'WEST', 'LEFT-UP'): 53,
    ('UP', 'WEST', 'RIGHT-UP'): 54,
    ('UP', 'WEST', 'DOWN-LEFT-RIGHT'): 55,
    ('UP', 'WEST', 'DOWN-LEFT-UP'): 56,
    ('UP', 'WEST', 'DOWN-RIGHT-UP'): 57,
    ('UP', 'WEST', 'LEFT-RIGHT-UP'): 58,
    ('UP', 'WEST', 'DOWN-LEFT-RIGHT-UP'): 59,
    ('UP', 'EAST', 'DOWN'): 60,
    ('UP', 'EAST', 'LEFT'): 61,
    ('UP', 'EAST', 'RIGHT'): 62,
    ('UP', 'EAST', 'UP'): 63,
    ('UP', 'EAST', 'DOWN-LEFT'): 64,
    ('UP', 'EAST', 'DOWN-RIGHT'): 65,
    ('UP', 'EAST', 'DOWN-UP'): 66,
    ('UP', 'EAST', 'LEFT-RIGHT'): 67,
    ('UP', 'EAST', 'LEFT-UP'): 68,
    ('UP', 'EAST', 'RIGHT-UP'): 69,
    ('UP', 'EAST', 'DOWN-LEFT-RIGHT'): 70,
    ('UP', 'EAST', 'DOWN-LEFT-UP'): 71,
    ('UP', 'EAST', 'DOWN-RIGHT-UP'): 72,
    ('UP', 'EAST', 'LEFT-RIGHT-UP'): 73,
    ('UP', 'EAST', 'DOWN-LEFT-RIGHT-UP'): 74,
    ('UP', 'NORTH-EAST', 'DOWN'): 75,
    ('UP', 'NORTH-EAST', 'LEFT'): 76,
    ('UP', 'NORTH-EAST', 'RIGHT'): 77,
    ('UP', 'NORTH-EAST', 'UP'): 78,
    ('UP', 'NORTH-EAST', 'DOWN-LEFT'): 79,
    ('UP', 'NORTH-EAST', 'DOWN-RIGHT'): 80,
    ('UP', 'NORTH-EAST', 'DOWN-UP'): 81,
    ('UP', 'NORTH-EAST', 'LEFT-RIGHT'): 82,
    ('UP', 'NORTH-EAST', 'LEFT-UP'): 83,
    ('UP', 'NORTH-EAST', 'RIGHT-UP'): 84,
    ('UP', 'NORTH-EAST', 'DOWN-LEFT-RIGHT'): 85,
    ('UP', 'NORTH-EAST', 'DOWN-LEFT-UP'): 86,
    ('UP', 'NORTH-EAST', 'DOWN-RIGHT-UP'): 87,
    ('UP', 'NORTH-EAST', 'LEFT-RIGHT-UP'): 88,
    ('UP', 'NORTH-EAST', 'DOWN-LEFT-RIGHT-UP'): 89,
    ('UP', 'NORTH-WEST', 'DOWN'): 90,
    ('UP', 'NORTH-WEST', 'LEFT'): 91,
    ('UP', 'NORTH-WEST', 'RIGHT'): 92,
    ('UP', 'NORTH-WEST', 'UP'): 93,
    ('UP', 'NORTH-WEST', 'DOWN-LEFT'): 94,
    ('UP', 'NORTH-WEST', 'DOWN-RIGHT'): 95,
    ('UP', 'NORTH-WEST', 'DOWN-UP'): 96,
    ('UP', 'NORTH-WEST', 'LEFT-RIGHT'): 97,
    ('UP', 'NORTH-WEST', 'LEFT-UP'): 98,
    ('UP', 'NORTH-WEST', 'RIGHT-UP'): 99,
    ('UP', 'NORTH-WEST', 'DOWN-LEFT-RIGHT'): 100,
    ('UP', 'NORTH-WEST', 'DOWN-LEFT-UP'): 101,
    ('UP', 'NORTH-WEST', 'DOWN-RIGHT-UP'): 102,
    ('UP', 'NORTH-WEST', 'LEFT-RIGHT-UP'): 103,
    ('UP', 'NORTH-WEST', 'DOWN-LEFT-RIGHT-UP'): 104,
    ('UP', 'SOUTH-EAST', 'DOWN'): 105,
    ('UP', 'SOUTH-EAST', 'LEFT'): 106,
    ('UP', 'SOUTH-EAST', 'RIGHT'): 107,
    ('UP', 'SOUTH-EAST', 'UP'): 108,
    ('UP', 'SOUTH-EAST', 'DOWN-LEFT'): 109,
    ('UP', 'SOUTH-EAST', 'DOWN-RIGHT'): 110,
    ('UP', 'SOUTH-EAST', 'DOWN-UP'): 111,
    ('UP', 'SOUTH-EAST', 'LEFT-RIGHT'): 112,
    ('UP', 'SOUTH-EAST', 'LEFT-UP'): 113,
    ('UP', 'SOUTH-EAST', 'RIGHT-UP'): 114,
    ('UP', 'SOUTH-EAST', 'DOWN-LEFT-RIGHT'): 115,
    ('UP', 'SOUTH-EAST', 'DOWN-LEFT-UP'): 116,
    ('UP', 'SOUTH-EAST', 'DOWN-RIGHT-UP'): 117,
    ('UP', 'SOUTH-EAST', 'LEFT-RIGHT-UP'): 118,
    ('UP', 'SOUTH-EAST', 'DOWN-LEFT-RIGHT-UP'): 119,
    ('UP', 'SOUTH-WEST', 'DOWN'): 120,
    ('UP', 'SOUTH-WEST', 'LEFT'): 121,
    ('UP', 'SOUTH-WEST', 'RIGHT'): 122,
    ('UP', 'SOUTH-WEST', 'UP'): 123,
    ('UP', 'SOUTH-WEST', 'DOWN-LEFT'): 124,
    ('UP', 'SOUTH-WEST', 'DOWN-RIGHT'): 125,
    ('UP', 'SOUTH-WEST', 'DOWN-UP'): 126,
    ('UP', 'SOUTH-WEST', 'LEFT-RIGHT'): 127,
    ('UP', 'SOUTH-WEST', 'LEFT-UP'): 128,
    ('UP', 'SOUTH-WEST', 'RIGHT-UP'): 129,
    ('UP', 'SOUTH-WEST', 'DOWN-LEFT-RIGHT'): 130,
    ('UP', 'SOUTH-WEST', 'DOWN-LEFT-UP'): 131,
    ('UP', 'SOUTH-WEST', 'DOWN-RIGHT-UP'): 132,
    ('UP', 'SOUTH-WEST', 'LEFT-RIGHT-UP'): 133,
    ('UP', 'SOUTH-WEST', 'DOWN-LEFT-RIGHT-UP'): 134,
    ('DOWN', 'EAT', 'DOWN'): 135,
    ('DOWN', 'EAT', 'LEFT'): 136,
    ('DOWN', 'EAT', 'RIGHT'): 137,
    ('DOWN', 'EAT', 'UP'): 138,
    ('DOWN', 'EAT', 'DOWN-LEFT'): 139,
    ('DOWN', 'EAT', 'DOWN-RIGHT'): 140,
    ('DOWN', 'EAT', 'DOWN-UP'): 141,
    ('DOWN', 'EAT', 'LEFT-RIGHT'): 142,
    ('DOWN', 'EAT', 'LEFT-UP'): 143,
    ('DOWN', 'EAT', 'RIGHT-UP'): 144,
    ('DOWN', 'EAT', 'DOWN-LEFT-RIGHT'): 145,
    ('DOWN', 'EAT', 'DOWN-LEFT-UP'): 146,
    ('DOWN', 'EAT', 'DOWN-RIGHT-UP'): 147,
    ('DOWN', 'EAT', 'LEFT-RIGHT-UP'): 148,
    ('DOWN', 'EAT', 'DOWN-LEFT-RIGHT-UP'): 149,
    ('DOWN', 'NORTH', 'DOWN'): 150,
    ('DOWN', 'NORTH', 'LEFT'): 151,
    ('DOWN', 'NORTH', 'RIGHT'): 152,
    ('DOWN', 'NORTH', 'UP'): 153,
    ('DOWN', 'NORTH', 'DOWN-LEFT'): 154,
    ('DOWN', 'NORTH', 'DOWN-RIGHT'): 155,
    ('DOWN', 'NORTH', 'DOWN-UP'): 156,
    ('DOWN', 'NORTH', 'LEFT-RIGHT'): 157,
    ('DOWN', 'NORTH', 'LEFT-UP'): 158,
    ('DOWN', 'NORTH', 'RIGHT-UP'): 159,
    ('DOWN', 'NORTH', 'DOWN-LEFT-RIGHT'): 160,
    ('DOWN', 'NORTH', 'DOWN-LEFT-UP'): 161,
    ('DOWN', 'NORTH', 'DOWN-RIGHT-UP'): 162,
    ('DOWN', 'NORTH', 'LEFT-RIGHT-UP'): 163,
    ('DOWN', 'NORTH', 'DOWN-LEFT-RIGHT-UP'): 164,
    ('DOWN', 'SOUTH', 'DOWN'): 165,
    ('DOWN', 'SOUTH', 'LEFT'): 166,
    ('DOWN', 'SOUTH', 'RIGHT'): 167,
    ('DOWN', 'SOUTH', 'UP'): 168,
    ('DOWN', 'SOUTH', 'DOWN-LEFT'): 169,
    ('DOWN', 'SOUTH', 'DOWN-RIGHT'): 170,
    ('DOWN', 'SOUTH', 'DOWN-UP'): 171,
    ('DOWN', 'SOUTH', 'LEFT-RIGHT'): 172,
    ('DOWN', 'SOUTH', 'LEFT-UP'): 173,
    ('DOWN', 'SOUTH', 'RIGHT-UP'): 174,
    ('DOWN', 'SOUTH', 'DOWN-LEFT-RIGHT'): 175,
    ('DOWN', 'SOUTH', 'DOWN-LEFT-UP'): 176,
    ('DOWN', 'SOUTH', 'DOWN-RIGHT-UP'): 177,
    ('DOWN', 'SOUTH', 'LEFT-RIGHT-UP'): 178,
    ('DOWN', 'SOUTH', 'DOWN-LEFT-RIGHT-UP'): 179,
    ('DOWN', 'WEST', 'DOWN'): 180,
    ('DOWN', 'WEST', 'LEFT'): 181,
    ('DOWN', 'WEST', 'RIGHT'): 182,
    ('DOWN', 'WEST', 'UP'): 183,
    ('DOWN', 'WEST', 'DOWN-LEFT'): 184,
    ('DOWN', 'WEST', 'DOWN-RIGHT'): 185,
    ('DOWN', 'WEST', 'DOWN-UP'): 186,
    ('DOWN', 'WEST', 'LEFT-RIGHT'): 187,
    ('DOWN', 'WEST', 'LEFT-UP'): 188,
    ('DOWN', 'WEST', 'RIGHT-UP'): 189,
    ('DOWN', 'WEST', 'DOWN-LEFT-RIGHT'): 190,
    ('DOWN', 'WEST', 'DOWN-LEFT-UP'): 191,
    ('DOWN', 'WEST', 'DOWN-RIGHT-UP'): 192,
    ('DOWN', 'WEST', 'LEFT-RIGHT-UP'): 193,
    ('DOWN', 'WEST', 'DOWN-LEFT-RIGHT-UP'): 194,
    ('DOWN', 'EAST', 'DOWN'): 195,
    ('DOWN', 'EAST', 'LEFT'): 196,
    ('DOWN', 'EAST', 'RIGHT'): 197,
    ('DOWN', 'EAST', 'UP'): 198,
    ('DOWN', 'EAST', 'DOWN-LEFT'): 199,
    ('DOWN', 'EAST', 'DOWN-RIGHT'): 200,
    ('DOWN', 'EAST', 'DOWN-UP'): 201,
    ('DOWN', 'EAST', 'LEFT-RIGHT'): 202,
    ('DOWN', 'EAST', 'LEFT-UP'): 203,
    ('DOWN', 'EAST', 'RIGHT-UP'): 204,
    ('DOWN', 'EAST', 'DOWN-LEFT-RIGHT'): 205,
    ('DOWN', 'EAST', 'DOWN-LEFT-UP'): 206,
    ('DOWN', 'EAST', 'DOWN-RIGHT-UP'): 207,
    ('DOWN', 'EAST', 'LEFT-RIGHT-UP'): 208,
    ('DOWN', 'EAST', 'DOWN-LEFT-RIGHT-UP'): 209,
    ('DOWN', 'NORTH-EAST', 'DOWN'): 210,
    ('DOWN', 'NORTH-EAST', 'LEFT'): 211,
    ('DOWN', 'NORTH-EAST', 'RIGHT'): 212,
    ('DOWN', 'NORTH-EAST', 'UP'): 213,
    ('DOWN', 'NORTH-EAST', 'DOWN-LEFT'): 214,
    ('DOWN', 'NORTH-EAST', 'DOWN-RIGHT'): 215,
    ('DOWN', 'NORTH-EAST', 'DOWN-UP'): 216,
    ('DOWN', 'NORTH-EAST', 'LEFT-RIGHT'): 217,
    ('DOWN', 'NORTH-EAST', 'LEFT-UP'): 218,
    ('DOWN', 'NORTH-EAST', 'RIGHT-UP'): 219,
    ('DOWN', 'NORTH-EAST', 'DOWN-LEFT-RIGHT'): 220,
    ('DOWN', 'NORTH-EAST', 'DOWN-LEFT-UP'): 221,
    ('DOWN', 'NORTH-EAST', 'DOWN-RIGHT-UP'): 222,
    ('DOWN', 'NORTH-EAST', 'LEFT-RIGHT-UP'): 223,
    ('DOWN', 'NORTH-EAST', 'DOWN-LEFT-RIGHT-UP'): 224,
    ('DOWN', 'NORTH-WEST', 'DOWN'): 225,
    ('DOWN', 'NORTH-WEST', 'LEFT'): 226,
    ('DOWN', 'NORTH-WEST', 'RIGHT'): 227,
    ('DOWN', 'NORTH-WEST', 'UP'): 228,
    ('DOWN', 'NORTH-WEST', 'DOWN-LEFT'): 229,
    ('DOWN', 'NORTH-WEST', 'DOWN-RIGHT'): 230,
    ('DOWN', 'NORTH-WEST', 'DOWN-UP'): 231,
    ('DOWN', 'NORTH-WEST', 'LEFT-RIGHT'): 232,
    ('DOWN', 'NORTH-WEST', 'LEFT-UP'): 233,
    ('DOWN', 'NORTH-WEST', 'RIGHT-UP'): 234,
    ('DOWN', 'NORTH-WEST', 'DOWN-LEFT-RIGHT'): 235,
    ('DOWN', 'NORTH-WEST', 'DOWN-LEFT-UP'): 236,
    ('DOWN', 'NORTH-WEST', 'DOWN-RIGHT-UP'): 237,
    ('DOWN', 'NORTH-WEST', 'LEFT-RIGHT-UP'): 238,
    ('DOWN', 'NORTH-WEST', 'DOWN-LEFT-RIGHT-UP'): 239,
    ('DOWN', 'SOUTH-EAST', 'DOWN'): 240,
    ('DOWN', 'SOUTH-EAST', 'LEFT'): 241,
    ('DOWN', 'SOUTH-EAST', 'RIGHT'): 242,
    ('DOWN', 'SOUTH-EAST', 'UP'): 243,
    ('DOWN', 'SOUTH-EAST', 'DOWN-LEFT'): 244,
    ('DOWN', 'SOUTH-EAST', 'DOWN-RIGHT'): 245,
    ('DOWN', 'SOUTH-EAST', 'DOWN-UP'): 246,
    ('DOWN', 'SOUTH-EAST', 'LEFT-RIGHT'): 247,
    ('DOWN', 'SOUTH-EAST', 'LEFT-UP'): 248,
    ('DOWN', 'SOUTH-EAST', 'RIGHT-UP'): 249,
    ('DOWN', 'SOUTH-EAST', 'DOWN-LEFT-RIGHT'): 250,
    ('DOWN', 'SOUTH-EAST', 'DOWN-LEFT-UP'): 251,
    ('DOWN', 'SOUTH-EAST', 'DOWN-RIGHT-UP'): 252,
    ('DOWN', 'SOUTH-EAST', 'LEFT-RIGHT-UP'): 253,
    ('DOWN', 'SOUTH-EAST', 'DOWN-LEFT-RIGHT-UP'): 254,
    ('DOWN', 'SOUTH-WEST', 'DOWN'): 255,
    ('DOWN', 'SOUTH-WEST', 'LEFT'): 256,
    ('DOWN', 'SOUTH-WEST', 'RIGHT'): 257,
    ('DOWN', 'SOUTH-WEST', 'UP'): 258,
    ('DOWN', 'SOUTH-WEST', 'DOWN-LEFT'): 259,
    ('DOWN', 'SOUTH-WEST', 'DOWN-RIGHT'): 260,
    ('DOWN', 'SOUTH-WEST', 'DOWN-UP'): 261,
    ('DOWN', 'SOUTH-WEST', 'LEFT-RIGHT'): 262,
    ('DOWN', 'SOUTH-WEST', 'LEFT-UP'): 263,
    ('DOWN', 'SOUTH-WEST', 'RIGHT-UP'): 264,
    ('DOWN', 'SOUTH-WEST', 'DOWN-LEFT-RIGHT'): 265,
    ('DOWN', 'SOUTH-WEST', 'DOWN-LEFT-UP'): 266,
    ('DOWN', 'SOUTH-WEST', 'DOWN-RIGHT-UP'): 267,
    ('DOWN', 'SOUTH-WEST', 'LEFT-RIGHT-UP'): 268,
    ('DOWN', 'SOUTH-WEST', 'DOWN-LEFT-RIGHT-UP'): 269,
    ('LEFT', 'EAT', 'DOWN'): 270,
    ('LEFT', 'EAT', 'LEFT'): 271,
    ('LEFT', 'EAT', 'RIGHT'): 272,
    ('LEFT', 'EAT', 'UP'): 273,
    ('LEFT', 'EAT', 'DOWN-LEFT'): 274,
    ('LEFT', 'EAT', 'DOWN-RIGHT'): 275,
    ('LEFT', 'EAT', 'DOWN-UP'): 276,
    ('LEFT', 'EAT', 'LEFT-RIGHT'): 277,
    ('LEFT', 'EAT', 'LEFT-UP'): 278,
    ('LEFT', 'EAT', 'RIGHT-UP'): 279,
    ('LEFT', 'EAT', 'DOWN-LEFT-RIGHT'): 280,
    ('LEFT', 'EAT', 'DOWN-LEFT-UP'): 281,
    ('LEFT', 'EAT', 'DOWN-RIGHT-UP'): 282,
    ('LEFT', 'EAT', 'LEFT-RIGHT-UP'): 283,
    ('LEFT', 'EAT', 'DOWN-LEFT-RIGHT-UP'): 284,
    ('LEFT', 'NORTH', 'DOWN'): 285,
    ('LEFT', 'NORTH', 'LEFT'): 286,
    ('LEFT', 'NORTH', 'RIGHT'): 287,
    ('LEFT', 'NORTH', 'UP'): 288,
    ('LEFT', 'NORTH', 'DOWN-LEFT'): 289,
    ('LEFT', 'NORTH', 'DOWN-RIGHT'): 290,
    ('LEFT', 'NORTH', 'DOWN-UP'): 291,
    ('LEFT', 'NORTH', 'LEFT-RIGHT'): 292,
    ('LEFT', 'NORTH', 'LEFT-UP'): 293,
    ('LEFT', 'NORTH', 'RIGHT-UP'): 294,
    ('LEFT', 'NORTH', 'DOWN-LEFT-RIGHT'): 295,
    ('LEFT', 'NORTH', 'DOWN-LEFT-UP'): 296,
    ('LEFT', 'NORTH', 'DOWN-RIGHT-UP'): 297,
    ('LEFT', 'NORTH', 'LEFT-RIGHT-UP'): 298,
    ('LEFT', 'NORTH', 'DOWN-LEFT-RIGHT-UP'): 299,
    ('LEFT', 'SOUTH', 'DOWN'): 300,
    ('LEFT', 'SOUTH', 'LEFT'): 301,
    ('LEFT', 'SOUTH', 'RIGHT'): 302,
    ('LEFT', 'SOUTH', 'UP'): 303,
    ('LEFT', 'SOUTH', 'DOWN-LEFT'): 304,
    ('LEFT', 'SOUTH', 'DOWN-RIGHT'): 305,
    ('LEFT', 'SOUTH', 'DOWN-UP'): 306,
    ('LEFT', 'SOUTH', 'LEFT-RIGHT'): 307,
    ('LEFT', 'SOUTH', 'LEFT-UP'): 308,
    ('LEFT', 'SOUTH', 'RIGHT-UP'): 309,
    ('LEFT', 'SOUTH', 'DOWN-LEFT-RIGHT'): 310,
    ('LEFT', 'SOUTH', 'DOWN-LEFT-UP'): 311,
    ('LEFT', 'SOUTH', 'DOWN-RIGHT-UP'): 312,
    ('LEFT', 'SOUTH', 'LEFT-RIGHT-UP'): 313,
    ('LEFT', 'SOUTH', 'DOWN-LEFT-RIGHT-UP'): 314,
    ('LEFT', 'WEST', 'DOWN'): 315,
    ('LEFT', 'WEST', 'LEFT'): 316,
    ('LEFT', 'WEST', 'RIGHT'): 317,
    ('LEFT', 'WEST', 'UP'): 318,
    ('LEFT', 'WEST', 'DOWN-LEFT'): 319,
    ('LEFT', 'WEST', 'DOWN-RIGHT'): 320,
    ('LEFT', 'WEST', 'DOWN-UP'): 321,
    ('LEFT', 'WEST', 'LEFT-RIGHT'): 322,
    ('LEFT', 'WEST', 'LEFT-UP'): 323,
    ('LEFT', 'WEST', 'RIGHT-UP'): 324,
    ('LEFT', 'WEST', 'DOWN-LEFT-RIGHT'): 325,
    ('LEFT', 'WEST', 'DOWN-LEFT-UP'): 326,
    ('LEFT', 'WEST', 'DOWN-RIGHT-UP'): 327,
    ('LEFT', 'WEST', 'LEFT-RIGHT-UP'): 328,
    ('LEFT', 'WEST', 'DOWN-LEFT-RIGHT-UP'): 329,
    ('LEFT', 'EAST', 'DOWN'): 330,
    ('LEFT', 'EAST', 'LEFT'): 331,
    ('LEFT', 'EAST', 'RIGHT'): 332,
    ('LEFT', 'EAST', 'UP'): 333,
    ('LEFT', 'EAST', 'DOWN-LEFT'): 334,
    ('LEFT', 'EAST', 'DOWN-RIGHT'): 335,
    ('LEFT', 'EAST', 'DOWN-UP'): 336,
    ('LEFT', 'EAST', 'LEFT-RIGHT'): 337,
    ('LEFT', 'EAST', 'LEFT-UP'): 338,
    ('LEFT', 'EAST', 'RIGHT-UP'): 339,
    ('LEFT', 'EAST', 'DOWN-LEFT-RIGHT'): 340,
    ('LEFT', 'EAST', 'DOWN-LEFT-UP'): 341,
    ('LEFT', 'EAST', 'DOWN-RIGHT-UP'): 342,
    ('LEFT', 'EAST', 'LEFT-RIGHT-UP'): 343,
    ('LEFT', 'EAST', 'DOWN-LEFT-RIGHT-UP'): 344,
    ('LEFT', 'NORTH-EAST', 'DOWN'): 345,
    ('LEFT', 'NORTH-EAST', 'LEFT'): 346,
    ('LEFT', 'NORTH-EAST', 'RIGHT'): 347,
    ('LEFT', 'NORTH-EAST', 'UP'): 348,
    ('LEFT', 'NORTH-EAST', 'DOWN-LEFT'): 349,
    ('LEFT', 'NORTH-EAST', 'DOWN-RIGHT'): 350,
    ('LEFT', 'NORTH-EAST', 'DOWN-UP'): 351,
    ('LEFT', 'NORTH-EAST', 'LEFT-RIGHT'): 352,
    ('LEFT', 'NORTH-EAST', 'LEFT-UP'): 353,
    ('LEFT', 'NORTH-EAST', 'RIGHT-UP'): 354,
    ('LEFT', 'NORTH-EAST', 'DOWN-LEFT-RIGHT'): 355,
    ('LEFT', 'NORTH-EAST', 'DOWN-LEFT-UP'): 356,
    ('LEFT', 'NORTH-EAST', 'DOWN-RIGHT-UP'): 357,
    ('LEFT', 'NORTH-EAST', 'LEFT-RIGHT-UP'): 358,
    ('LEFT', 'NORTH-EAST', 'DOWN-LEFT-RIGHT-UP'): 359,
    ('LEFT', 'NORTH-WEST', 'DOWN'): 360,
    ('LEFT', 'NORTH-WEST', 'LEFT'): 361,
    ('LEFT', 'NORTH-WEST', 'RIGHT'): 362,
    ('LEFT', 'NORTH-WEST', 'UP'): 363,
    ('LEFT', 'NORTH-WEST', 'DOWN-LEFT'): 364,
    ('LEFT', 'NORTH-WEST', 'DOWN-RIGHT'): 365,
    ('LEFT', 'NORTH-WEST', 'DOWN-UP'): 366,
    ('LEFT', 'NORTH-WEST', 'LEFT-RIGHT'): 367,
    ('LEFT', 'NORTH-WEST', 'LEFT-UP'): 368,
    ('LEFT', 'NORTH-WEST', 'RIGHT-UP'): 369,
    ('LEFT', 'NORTH-WEST', 'DOWN-LEFT-RIGHT'): 370,
    ('LEFT', 'NORTH-WEST', 'DOWN-LEFT-UP'): 371,
    ('LEFT', 'NORTH-WEST', 'DOWN-RIGHT-UP'): 372,
    ('LEFT', 'NORTH-WEST', 'LEFT-RIGHT-UP'): 373,
    ('LEFT', 'NORTH-WEST', 'DOWN-LEFT-RIGHT-UP'): 374,
    ('LEFT', 'SOUTH-EAST', 'DOWN'): 375,
    ('LEFT', 'SOUTH-EAST', 'LEFT'): 376,
    ('LEFT', 'SOUTH-EAST', 'RIGHT'): 377,
    ('LEFT', 'SOUTH-EAST', 'UP'): 378,
    ('LEFT', 'SOUTH-EAST', 'DOWN-LEFT'): 379,
    ('LEFT', 'SOUTH-EAST', 'DOWN-RIGHT'): 380,
    ('LEFT', 'SOUTH-EAST', 'DOWN-UP'): 381,
    ('LEFT', 'SOUTH-EAST', 'LEFT-RIGHT'): 382,
    ('LEFT', 'SOUTH-EAST', 'LEFT-UP'): 383,
    ('LEFT', 'SOUTH-EAST', 'RIGHT-UP'): 384,
    ('LEFT', 'SOUTH-EAST', 'DOWN-LEFT-RIGHT'): 385,
    ('LEFT', 'SOUTH-EAST', 'DOWN-LEFT-UP'): 386,
    ('LEFT', 'SOUTH-EAST', 'DOWN-RIGHT-UP'): 387,
    ('LEFT', 'SOUTH-EAST', 'LEFT-RIGHT-UP'): 388,
    ('LEFT', 'SOUTH-EAST', 'DOWN-LEFT-RIGHT-UP'): 389,
    ('LEFT', 'SOUTH-WEST', 'DOWN'): 390,
    ('LEFT', 'SOUTH-WEST', 'LEFT'): 391,
    ('LEFT', 'SOUTH-WEST', 'RIGHT'): 392,
    ('LEFT', 'SOUTH-WEST', 'UP'): 393,
    ('LEFT', 'SOUTH-WEST', 'DOWN-LEFT'): 394,
    ('LEFT', 'SOUTH-WEST', 'DOWN-RIGHT'): 395,
    ('LEFT', 'SOUTH-WEST', 'DOWN-UP'): 396,
    ('LEFT', 'SOUTH-WEST', 'LEFT-RIGHT'): 397,
    ('LEFT', 'SOUTH-WEST', 'LEFT-UP'): 398,
    ('LEFT', 'SOUTH-WEST', 'RIGHT-UP'): 399,
    ('LEFT', 'SOUTH-WEST', 'DOWN-LEFT-RIGHT'): 400,
    ('LEFT', 'SOUTH-WEST', 'DOWN-LEFT-UP'): 401,
    ('LEFT', 'SOUTH-WEST', 'DOWN-RIGHT-UP'): 402,
    ('LEFT', 'SOUTH-WEST', 'LEFT-RIGHT-UP'): 403,
    ('LEFT', 'SOUTH-WEST', 'DOWN-LEFT-RIGHT-UP'): 404,
    ('RIGHT', 'EAT', 'DOWN'): 405,
    ('RIGHT', 'EAT', 'LEFT'): 406,
    ('RIGHT', 'EAT', 'RIGHT'): 407,
    ('RIGHT', 'EAT', 'UP'): 408,
    ('RIGHT', 'EAT', 'DOWN-LEFT'): 409,
    ('RIGHT', 'EAT', 'DOWN-RIGHT'): 410,
    ('RIGHT', 'EAT', 'DOWN-UP'): 411,
    ('RIGHT', 'EAT', 'LEFT-RIGHT'): 412,
    ('RIGHT', 'EAT', 'LEFT-UP'): 413,
    ('RIGHT', 'EAT', 'RIGHT-UP'): 414,
    ('RIGHT', 'EAT', 'DOWN-LEFT-RIGHT'): 415,
    ('RIGHT', 'EAT', 'DOWN-LEFT-UP'): 416,
    ('RIGHT', 'EAT', 'DOWN-RIGHT-UP'): 417,
    ('RIGHT', 'EAT', 'LEFT-RIGHT-UP'): 418,
    ('RIGHT', 'EAT', 'DOWN-LEFT-RIGHT-UP'): 419,
    ('RIGHT', 'NORTH', 'DOWN'): 420,
    ('RIGHT', 'NORTH', 'LEFT'): 421,
    ('RIGHT', 'NORTH', 'RIGHT'): 422,
    ('RIGHT', 'NORTH', 'UP'): 423,
    ('RIGHT', 'NORTH', 'DOWN-LEFT'): 424,
    ('RIGHT', 'NORTH', 'DOWN-RIGHT'): 425,
    ('RIGHT', 'NORTH', 'DOWN-UP'): 426,
    ('RIGHT', 'NORTH', 'LEFT-RIGHT'): 427,
    ('RIGHT', 'NORTH', 'LEFT-UP'): 428,
    ('RIGHT', 'NORTH', 'RIGHT-UP'): 429,
    ('RIGHT', 'NORTH', 'DOWN-LEFT-RIGHT'): 430,
    ('RIGHT', 'NORTH', 'DOWN-LEFT-UP'): 431,
    ('RIGHT', 'NORTH', 'DOWN-RIGHT-UP'): 432,
    ('RIGHT', 'NORTH', 'LEFT-RIGHT-UP'): 433,
    ('RIGHT', 'NORTH', 'DOWN-LEFT-RIGHT-UP'): 434,
    ('RIGHT', 'SOUTH', 'DOWN'): 435,
    ('RIGHT', 'SOUTH', 'LEFT'): 436,
    ('RIGHT', 'SOUTH', 'RIGHT'): 437,
    ('RIGHT', 'SOUTH', 'UP'): 438,
    ('RIGHT', 'SOUTH', 'DOWN-LEFT'): 439,
    ('RIGHT', 'SOUTH', 'DOWN-RIGHT'): 440,
    ('RIGHT', 'SOUTH', 'DOWN-UP'): 441,
    ('RIGHT', 'SOUTH', 'LEFT-RIGHT'): 442,
    ('RIGHT', 'SOUTH', 'LEFT-UP'): 443,
    ('RIGHT', 'SOUTH', 'RIGHT-UP'): 444,
    ('RIGHT', 'SOUTH', 'DOWN-LEFT-RIGHT'): 445,
    ('RIGHT', 'SOUTH', 'DOWN-LEFT-UP'): 446,
    ('RIGHT', 'SOUTH', 'DOWN-RIGHT-UP'): 447,
    ('RIGHT', 'SOUTH', 'LEFT-RIGHT-UP'): 448,
    ('RIGHT', 'SOUTH', 'DOWN-LEFT-RIGHT-UP'): 449,
    ('RIGHT', 'WEST', 'DOWN'): 450,
    ('RIGHT', 'WEST', 'LEFT'): 451,
    ('RIGHT', 'WEST', 'RIGHT'): 452,
    ('RIGHT', 'WEST', 'UP'): 453,
    ('RIGHT', 'WEST', 'DOWN-LEFT'): 454,
    ('RIGHT', 'WEST', 'DOWN-RIGHT'): 455,
    ('RIGHT', 'WEST', 'DOWN-UP'): 456,
    ('RIGHT', 'WEST', 'LEFT-RIGHT'): 457,
    ('RIGHT', 'WEST', 'LEFT-UP'): 458,
    ('RIGHT', 'WEST', 'RIGHT-UP'): 459,
    ('RIGHT', 'WEST', 'DOWN-LEFT-RIGHT'): 460,
    ('RIGHT', 'WEST', 'DOWN-LEFT-UP'): 461,
    ('RIGHT', 'WEST', 'DOWN-RIGHT-UP'): 462,
    ('RIGHT', 'WEST', 'LEFT-RIGHT-UP'): 463,
    ('RIGHT', 'WEST', 'DOWN-LEFT-RIGHT-UP'): 464,
    ('RIGHT', 'EAST', 'DOWN'): 465,
    ('RIGHT', 'EAST', 'LEFT'): 466,
    ('RIGHT', 'EAST', 'RIGHT'): 467,
    ('RIGHT', 'EAST', 'UP'): 468,
    ('RIGHT', 'EAST', 'DOWN-LEFT'): 469,
    ('RIGHT', 'EAST', 'DOWN-RIGHT'): 470,
    ('RIGHT', 'EAST', 'DOWN-UP'): 471,
    ('RIGHT', 'EAST', 'LEFT-RIGHT'): 472,
    ('RIGHT', 'EAST', 'LEFT-UP'): 473,
    ('RIGHT', 'EAST', 'RIGHT-UP'): 474,
    ('RIGHT', 'EAST', 'DOWN-LEFT-RIGHT'): 475,
    ('RIGHT', 'EAST', 'DOWN-LEFT-UP'): 476,
    ('RIGHT', 'EAST', 'DOWN-RIGHT-UP'): 477,
    ('RIGHT', 'EAST', 'LEFT-RIGHT-UP'): 478,
    ('RIGHT', 'EAST', 'DOWN-LEFT-RIGHT-UP'): 479,
    ('RIGHT', 'NORTH-EAST', 'DOWN'): 480,
    ('RIGHT', 'NORTH-EAST', 'LEFT'): 481,
    ('RIGHT', 'NORTH-EAST', 'RIGHT'): 482,
    ('RIGHT', 'NORTH-EAST', 'UP'): 483,
    ('RIGHT', 'NORTH-EAST', 'DOWN-LEFT'): 484,
    ('RIGHT', 'NORTH-EAST', 'DOWN-RIGHT'): 485,
    ('RIGHT', 'NORTH-EAST', 'DOWN-UP'): 486,
    ('RIGHT', 'NORTH-EAST', 'LEFT-RIGHT'): 487,
    ('RIGHT', 'NORTH-EAST', 'LEFT-UP'): 488,
    ('RIGHT', 'NORTH-EAST', 'RIGHT-UP'): 489,
    ('RIGHT', 'NORTH-EAST', 'DOWN-LEFT-RIGHT'): 490,
    ('RIGHT', 'NORTH-EAST', 'DOWN-LEFT-UP'): 491,
    ('RIGHT', 'NORTH-EAST', 'DOWN-RIGHT-UP'): 492,
    ('RIGHT', 'NORTH-EAST', 'LEFT-RIGHT-UP'): 493,
    ('RIGHT', 'NORTH-EAST', 'DOWN-LEFT-RIGHT-UP'): 494,
    ('RIGHT', 'NORTH-WEST', 'DOWN'): 495,
    ('RIGHT', 'NORTH-WEST', 'LEFT'): 496,
    ('RIGHT', 'NORTH-WEST', 'RIGHT'): 497,
    ('RIGHT', 'NORTH-WEST', 'UP'): 498,
    ('RIGHT', 'NORTH-WEST', 'DOWN-LEFT'): 499,
    ('RIGHT', 'NORTH-WEST', 'DOWN-RIGHT'): 500,
    ('RIGHT', 'NORTH-WEST', 'DOWN-UP'): 501,
    ('RIGHT', 'NORTH-WEST', 'LEFT-RIGHT'): 502,
    ('RIGHT', 'NORTH-WEST', 'LEFT-UP'): 503,
    ('RIGHT', 'NORTH-WEST', 'RIGHT-UP'): 504,
    ('RIGHT', 'NORTH-WEST', 'DOWN-LEFT-RIGHT'): 505,
    ('RIGHT', 'NORTH-WEST', 'DOWN-LEFT-UP'): 506,
    ('RIGHT', 'NORTH-WEST', 'DOWN-RIGHT-UP'): 507,
    ('RIGHT', 'NORTH-WEST', 'LEFT-RIGHT-UP'): 508,
    ('RIGHT', 'NORTH-WEST', 'DOWN-LEFT-RIGHT-UP'): 509,
    ('RIGHT', 'SOUTH-EAST', 'DOWN'): 510,
    ('RIGHT', 'SOUTH-EAST', 'LEFT'): 511,
    ('RIGHT', 'SOUTH-EAST', 'RIGHT'): 512,
    ('RIGHT', 'SOUTH-EAST', 'UP'): 513,
    ('RIGHT', 'SOUTH-EAST', 'DOWN-LEFT'): 514,
    ('RIGHT', 'SOUTH-EAST', 'DOWN-RIGHT'): 515,
    ('RIGHT', 'SOUTH-EAST', 'DOWN-UP'): 516,
    ('RIGHT', 'SOUTH-EAST', 'LEFT-RIGHT'): 517,
    ('RIGHT', 'SOUTH-EAST', 'LEFT-UP'): 518,
    ('RIGHT', 'SOUTH-EAST', 'RIGHT-UP'): 519,
    ('RIGHT', 'SOUTH-EAST', 'DOWN-LEFT-RIGHT'): 520,
    ('RIGHT', 'SOUTH-EAST', 'DOWN-LEFT-UP'): 521,
    ('RIGHT', 'SOUTH-EAST', 'DOWN-RIGHT-UP'): 522,
    ('RIGHT', 'SOUTH-EAST', 'LEFT-RIGHT-UP'): 523,
    ('RIGHT', 'SOUTH-EAST', 'DOWN-LEFT-RIGHT-UP'): 524,
    ('RIGHT', 'SOUTH-WEST', 'DOWN'): 525,
    ('RIGHT', 'SOUTH-WEST', 'LEFT'): 526,
    ('RIGHT', 'SOUTH-WEST', 'RIGHT'): 527,
    ('RIGHT', 'SOUTH-WEST', 'UP'): 528,
    ('RIGHT', 'SOUTH-WEST', 'DOWN-LEFT'): 529,
    ('RIGHT', 'SOUTH-WEST', 'DOWN-RIGHT'): 530,
    ('RIGHT', 'SOUTH-WEST', 'DOWN-UP'): 531,
    ('RIGHT', 'SOUTH-WEST', 'LEFT-RIGHT'): 532,
    ('RIGHT', 'SOUTH-WEST', 'LEFT-UP'): 533,
    ('RIGHT', 'SOUTH-WEST', 'RIGHT-UP'): 534,
    ('RIGHT', 'SOUTH-WEST', 'DOWN-LEFT-RIGHT'): 535,
    ('RIGHT', 'SOUTH-WEST', 'DOWN-LEFT-UP'): 536,
    ('RIGHT', 'SOUTH-WEST', 'DOWN-RIGHT-UP'): 537,
    ('RIGHT', 'SOUTH-WEST', 'LEFT-RIGHT-UP'): 538,
    ('RIGHT', 'SOUTH-WEST', 'DOWN-LEFT-RIGHT-UP'): 539,
}
        self.alpha = alpha
        self.gamma = gamma
        self.epsilon = epsilon
        self.epsilon_min = epsilon_min
        self.epsilon_decay = epsilon_decay
        self.load_q_table()

    def choose_action(self, state, allowed_actions):
        if np.random.uniform(0, 1) < self.epsilon:
            action = random.choice(allowed_actions)  # Explore
        else:
            action = np.argmax(self.q_table[state])  # Exploit
            
        self.epsilon = max(self.epsilon_min, self.epsilon_decay * self.epsilon)
        return action

    def update_q_table(self, state, action, reward, next_state, terminal_state):
        # Your code here
        # Update the current Q-value using the Q-learning formula
        # if terminal_state:
        # Q(state,action) <- (1-self.alpha) Q(state,action) + self.alpha * (r + 0)
        # else:
        # Q(state,action) <- (1-self.alpha) Q(state,action) + self.alpha * (r + self.discount * max a' Q(nextState, a'))
        state = self.getStateIndex(state)
        action = self.getActionIndex(action)
        if terminal_state:  # terminal state
            future_value = 0
        else:
            next_stateIn = self.getStateIndex(next_state)
            future_value = np.max(self.q_table[next_stateIn])

        # Q-value update
        current_q_value = self.q_table[state][action]
        new_q_value = (1 - self.alpha) * current_q_value + self.alpha * (reward + self.gamma * future_value)

        # Update the Q-table with the new Q-value
        self.q_table[state][action] = new_q_value

    def save_q_table(self, filename="q_table.txt"):
        np.savetxt(filename, self.q_table)

    def load_q_table(self, filename="q_table.txt"):
        try:
            self.q_table = np.loadtxt(filename)
        except IOError:
            # If the file doesn't exist, initialize Q-table with zeros as per dimensions
            self.q_table = np.zeros((self.n_states, self.n_actions))

    def getActionIndex(self, action):
        return int(self.actions[action])

    def getStateIndex(self, state):
        return int(self.states[state])